[2024-04-14T04:18:10.307+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:18:10.309+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:18:10.311+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:18:10.310+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:18:10.320+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:18:10.318+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:18:10.320+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:18:10.334+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.031 seconds
[2024-04-14T04:18:40.457+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:18:40.457+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:18:40.458+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:18:40.458+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:18:40.461+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:18:40.461+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:18:40.462+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:18:40.473+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.020 seconds
[2024-04-14T04:19:10.558+0000] {processor.py:161} INFO - Started process (PID=155) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:19:10.560+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:19:10.563+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:19:10.562+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:19:10.567+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:19:10.566+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:19:10.568+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:19:10.602+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.049 seconds
[2024-04-14T04:19:40.727+0000] {processor.py:161} INFO - Started process (PID=217) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:19:40.729+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:19:40.733+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:19:40.732+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:19:40.745+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:19:40.741+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:19:40.746+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:19:40.813+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.107 seconds
[2024-04-14T04:20:11.081+0000] {processor.py:161} INFO - Started process (PID=279) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:20:11.083+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:20:11.088+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:20:11.087+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:20:11.095+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:20:11.094+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:20:11.095+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:20:11.114+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.055 seconds
[2024-04-14T04:20:41.283+0000] {processor.py:161} INFO - Started process (PID=341) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:20:41.285+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:20:41.287+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:20:41.287+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:20:41.294+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:20:41.293+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:20:41.294+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:20:41.322+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.049 seconds
[2024-04-14T04:21:11.663+0000] {processor.py:161} INFO - Started process (PID=403) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:21:11.664+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:21:11.667+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:21:11.667+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:21:11.672+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:21:11.671+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:21:11.673+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:21:11.691+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.036 seconds
[2024-04-14T04:21:41.872+0000] {processor.py:161} INFO - Started process (PID=465) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:21:41.875+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:21:41.878+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:21:41.877+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:21:41.885+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:21:41.884+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:21:41.886+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:21:41.901+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.038 seconds
[2024-04-14T04:22:11.963+0000] {processor.py:161} INFO - Started process (PID=527) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:22:11.964+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:22:11.967+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:22:11.967+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:22:11.974+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:22:11.972+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:22:11.975+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:22:12.000+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.052 seconds
[2024-04-14T04:22:42.773+0000] {processor.py:161} INFO - Started process (PID=589) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:22:42.782+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:22:42.789+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:22:42.787+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:22:42.815+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:22:42.810+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:22:42.817+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:22:42.945+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.196 seconds
[2024-04-14T04:23:13.183+0000] {processor.py:161} INFO - Started process (PID=651) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:23:13.185+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:23:13.189+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:23:13.188+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:23:13.197+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:23:13.195+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:23:13.198+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:23:13.241+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.069 seconds
[2024-04-14T04:23:43.700+0000] {processor.py:161} INFO - Started process (PID=713) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:23:43.701+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:23:43.704+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:23:43.704+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:23:43.711+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:23:43.710+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:23:43.711+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:23:43.754+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.060 seconds
[2024-04-14T04:24:13.980+0000] {processor.py:161} INFO - Started process (PID=775) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:24:13.982+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:24:13.986+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:24:13.985+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:24:13.994+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:24:13.992+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:24:13.994+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:24:14.025+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.053 seconds
[2024-04-14T04:24:44.561+0000] {processor.py:161} INFO - Started process (PID=837) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:24:44.563+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:24:44.568+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:24:44.566+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:24:44.582+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:24:44.580+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:24:44.582+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:24:44.635+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.079 seconds
[2024-04-14T04:25:15.077+0000] {processor.py:161} INFO - Started process (PID=899) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:25:15.081+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:25:15.087+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:25:15.086+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:25:15.098+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:25:15.096+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:25:15.099+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:25:15.124+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.061 seconds
[2024-04-14T04:25:45.934+0000] {processor.py:161} INFO - Started process (PID=961) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:25:45.935+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:25:45.938+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:25:45.938+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:25:45.944+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:25:45.943+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:25:45.944+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:25:45.990+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.067 seconds
[2024-04-14T04:26:16.263+0000] {processor.py:161} INFO - Started process (PID=1023) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:26:16.264+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:26:16.267+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:26:16.266+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:26:16.273+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:26:16.272+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:26:16.274+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:26:16.294+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.059 seconds
[2024-04-14T04:26:46.831+0000] {processor.py:161} INFO - Started process (PID=1085) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:26:46.833+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:26:46.837+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:26:46.837+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:26:46.844+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:26:46.843+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:26:46.844+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:26:46.865+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.056 seconds
[2024-04-14T04:27:17.052+0000] {processor.py:161} INFO - Started process (PID=1147) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:27:17.053+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:27:17.056+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:27:17.056+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:27:17.062+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:27:17.061+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:27:17.062+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:27:17.084+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.056 seconds
[2024-04-14T04:27:47.699+0000] {processor.py:161} INFO - Started process (PID=1209) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:27:47.703+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:27:47.706+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:27:47.706+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:27:47.721+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:27:47.718+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:27:47.726+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:27:47.744+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.060 seconds
[2024-04-14T04:28:18.272+0000] {processor.py:161} INFO - Started process (PID=1273) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:28:18.275+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:28:18.278+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:28:18.278+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:28:18.286+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:28:18.284+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:28:18.286+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:28:18.330+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.067 seconds
[2024-04-14T04:28:48.580+0000] {processor.py:161} INFO - Started process (PID=1335) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:28:48.582+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:28:48.585+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:28:48.585+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:28:48.593+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:28:48.592+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:28:48.594+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:28:48.627+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.054 seconds
[2024-04-14T04:29:19.334+0000] {processor.py:161} INFO - Started process (PID=1397) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:29:19.336+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:29:19.337+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:29:19.337+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:29:19.343+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:29:19.341+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:29:19.343+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:29:19.360+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.031 seconds
[2024-04-14T04:29:49.521+0000] {processor.py:161} INFO - Started process (PID=1458) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:29:49.522+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:29:49.523+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:29:49.523+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:29:49.528+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:29:49.527+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:29:49.528+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:29:49.543+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.032 seconds
[2024-04-14T04:30:19.783+0000] {processor.py:161} INFO - Started process (PID=1520) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:30:19.785+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:30:19.787+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:30:19.787+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:30:19.794+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:30:19.791+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:30:19.795+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:30:19.810+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.035 seconds
[2024-04-14T04:30:50.213+0000] {processor.py:161} INFO - Started process (PID=1582) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:30:50.214+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:30:50.217+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:30:50.217+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:30:50.222+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:30:50.221+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:30:50.223+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:30:50.239+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.032 seconds
[2024-04-14T04:31:20.786+0000] {processor.py:161} INFO - Started process (PID=1644) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:31:20.788+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:31:20.790+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:31:20.790+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:31:20.796+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:31:20.795+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:31:20.797+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:31:20.812+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.035 seconds
[2024-04-14T04:31:51.144+0000] {processor.py:161} INFO - Started process (PID=1706) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:31:51.146+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:31:51.148+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:31:51.148+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:31:51.154+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:31:51.153+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:31:51.155+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:31:51.174+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.040 seconds
[2024-04-14T04:32:21.513+0000] {processor.py:161} INFO - Started process (PID=1768) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:32:21.514+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:32:21.515+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:32:21.515+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:32:21.520+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:32:21.519+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:32:21.520+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:32:21.537+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.030 seconds
[2024-04-14T04:32:51.928+0000] {processor.py:161} INFO - Started process (PID=1830) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:32:51.928+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:32:51.930+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:32:51.929+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:32:51.935+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:32:51.934+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:32:51.936+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:32:51.969+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.046 seconds
[2024-04-14T04:33:22.299+0000] {processor.py:161} INFO - Started process (PID=1892) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:33:22.301+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:33:22.303+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:33:22.303+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:33:22.309+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:33:22.308+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:33:22.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:33:22.326+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.035 seconds
[2024-04-14T04:33:52.839+0000] {processor.py:161} INFO - Started process (PID=1953) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:33:52.840+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-14T04:33:52.843+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:33:52.843+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:33:52.851+0000] {logging_mixin.py:188} INFO - [2024-04-14T04:33:52.850+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-14T04:33:52.851+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-14T04:33:52.870+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.038 seconds
