[2024-04-13T05:51:04.177+0000] {processor.py:161} INFO - Started process (PID=2369) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:51:04.178+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T05:51:04.179+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:51:04.179+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:51:04.182+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:51:04.182+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T05:51:04.183+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:51:04.192+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.018 seconds
[2024-04-13T05:51:34.442+0000] {processor.py:161} INFO - Started process (PID=2420) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:51:34.443+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T05:51:34.445+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:51:34.445+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:51:34.453+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:51:34.451+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T05:51:34.454+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:51:34.472+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.039 seconds
[2024-04-13T05:52:04.587+0000] {processor.py:161} INFO - Started process (PID=2480) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:52:04.589+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T05:52:04.593+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:52:04.593+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:52:04.601+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:52:04.599+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T05:52:04.601+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:52:04.635+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.057 seconds
[2024-04-13T05:52:34.857+0000] {processor.py:161} INFO - Started process (PID=2540) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:52:34.859+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T05:52:34.861+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:52:34.861+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:52:34.870+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:52:34.868+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T05:52:34.871+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:52:34.888+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.041 seconds
[2024-04-13T05:53:05.353+0000] {processor.py:161} INFO - Started process (PID=2600) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:53:05.354+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T05:53:05.356+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:53:05.356+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:53:05.365+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:53:05.363+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T05:53:05.365+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:53:05.386+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.042 seconds
[2024-04-13T05:53:35.449+0000] {processor.py:161} INFO - Started process (PID=2660) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:53:35.450+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T05:53:35.452+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:53:35.452+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:53:35.460+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:53:35.458+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T05:53:35.461+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:53:35.477+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.036 seconds
[2024-04-13T05:54:06.152+0000] {processor.py:161} INFO - Started process (PID=2720) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:54:06.154+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T05:54:06.157+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:54:06.157+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:54:06.167+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:54:06.165+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T05:54:06.168+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:54:06.198+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.053 seconds
[2024-04-13T05:54:37.049+0000] {processor.py:161} INFO - Started process (PID=2781) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:54:37.050+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T05:54:37.052+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:54:37.052+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:54:37.060+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:54:37.059+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T05:54:37.061+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:54:37.078+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.038 seconds
[2024-04-13T05:55:07.488+0000] {processor.py:161} INFO - Started process (PID=2841) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:55:07.489+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T05:55:07.491+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:55:07.491+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:55:07.499+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:55:07.497+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T05:55:07.500+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:55:07.516+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.037 seconds
[2024-04-13T05:55:37.807+0000] {processor.py:161} INFO - Started process (PID=2901) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:55:37.808+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T05:55:37.810+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:55:37.810+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:55:37.819+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:55:37.817+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T05:55:37.820+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:55:37.837+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.038 seconds
[2024-04-13T05:56:07.997+0000] {processor.py:161} INFO - Started process (PID=2960) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:56:08.002+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T05:56:08.006+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:56:08.005+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:56:08.011+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:56:08.010+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T05:56:08.012+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:56:08.033+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.071 seconds
[2024-04-13T05:56:38.543+0000] {processor.py:161} INFO - Started process (PID=3020) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:56:38.544+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T05:56:38.546+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:56:38.546+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:56:38.554+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:56:38.552+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T05:56:38.555+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:56:38.575+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.039 seconds
[2024-04-13T05:57:08.867+0000] {processor.py:161} INFO - Started process (PID=3080) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:57:08.868+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T05:57:08.870+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:57:08.870+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:57:08.876+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:57:08.875+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T05:57:08.877+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:57:08.893+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.034 seconds
[2024-04-13T05:57:39.023+0000] {processor.py:161} INFO - Started process (PID=3140) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:57:39.025+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T05:57:39.027+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:57:39.027+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:57:39.034+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:57:39.032+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T05:57:39.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:57:39.051+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.037 seconds
[2024-04-13T05:58:09.751+0000] {processor.py:161} INFO - Started process (PID=3200) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:58:09.753+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T05:58:09.755+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:58:09.755+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:58:09.760+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:58:09.759+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T05:58:09.760+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:58:09.776+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.032 seconds
[2024-04-13T05:58:40.446+0000] {processor.py:161} INFO - Started process (PID=3260) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:58:40.448+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T05:58:40.451+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:58:40.451+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:58:40.463+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:58:40.460+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T05:58:40.464+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:58:40.482+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.049 seconds
[2024-04-13T05:59:10.499+0000] {processor.py:161} INFO - Started process (PID=3320) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:59:10.500+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T05:59:10.501+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:59:10.501+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:59:10.505+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:59:10.504+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T05:59:10.506+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:59:10.515+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.019 seconds
[2024-04-13T05:59:41.059+0000] {processor.py:161} INFO - Started process (PID=3373) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:59:41.062+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T05:59:41.066+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:59:41.065+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:59:41.081+0000] {logging_mixin.py:188} INFO - [2024-04-13T05:59:41.078+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T05:59:41.082+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T05:59:41.108+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.062 seconds
[2024-04-13T06:00:12.102+0000] {processor.py:161} INFO - Started process (PID=3432) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:00:12.103+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T06:00:12.104+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:00:12.104+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:00:12.110+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:00:12.108+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T06:00:12.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:00:12.124+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.027 seconds
[2024-04-13T06:00:42.379+0000] {processor.py:161} INFO - Started process (PID=3493) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:00:42.382+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T06:00:42.390+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:00:42.389+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:00:42.398+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:00:42.397+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T06:00:42.399+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:00:42.416+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.048 seconds
[2024-04-13T06:01:12.636+0000] {processor.py:161} INFO - Started process (PID=3553) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:01:12.637+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T06:01:12.638+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:01:12.638+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:01:12.643+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:01:12.642+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T06:01:12.643+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:01:12.654+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.022 seconds
[2024-04-13T06:01:42.704+0000] {processor.py:161} INFO - Started process (PID=3613) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:01:42.705+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T06:01:42.707+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:01:42.706+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:01:42.712+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:01:42.710+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T06:01:42.712+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:01:42.725+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.026 seconds
[2024-04-13T06:02:12.965+0000] {processor.py:161} INFO - Started process (PID=3673) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:02:12.966+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T06:02:12.968+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:02:12.968+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:02:12.973+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:02:12.972+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T06:02:12.973+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:02:12.993+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.046 seconds
[2024-04-13T06:02:43.212+0000] {processor.py:161} INFO - Started process (PID=3733) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:02:43.213+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T06:02:43.214+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:02:43.214+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:02:43.221+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:02:43.219+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T06:02:43.221+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:02:43.234+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.029 seconds
[2024-04-13T06:03:13.403+0000] {processor.py:161} INFO - Started process (PID=3793) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:03:13.404+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T06:03:13.407+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:03:13.406+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:03:13.412+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:03:13.411+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T06:03:13.413+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:03:13.426+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.031 seconds
[2024-04-13T06:03:43.735+0000] {processor.py:161} INFO - Started process (PID=3853) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:03:43.737+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T06:03:43.741+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:03:43.740+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:03:43.774+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:03:43.771+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T06:03:43.776+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:03:43.797+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.068 seconds
[2024-04-13T06:04:13.966+0000] {processor.py:161} INFO - Started process (PID=3913) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:04:13.967+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T06:04:13.969+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:04:13.968+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:04:13.974+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:04:13.972+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T06:04:13.974+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:04:13.995+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.034 seconds
[2024-04-13T06:04:44.541+0000] {processor.py:161} INFO - Started process (PID=3973) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:04:44.542+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T06:04:44.543+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:04:44.543+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:04:44.548+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:04:44.546+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T06:04:44.549+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:04:44.557+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.020 seconds
[2024-04-13T06:05:14.997+0000] {processor.py:161} INFO - Started process (PID=4033) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:05:14.997+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T06:05:14.998+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:05:14.998+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:05:15.002+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:05:15.001+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T06:05:15.002+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:05:15.015+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.023 seconds
[2024-04-13T06:05:45.175+0000] {processor.py:161} INFO - Started process (PID=4093) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:05:45.177+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T06:05:45.183+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:05:45.182+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:05:45.197+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:05:45.195+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T06:05:45.198+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:05:45.213+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.045 seconds
[2024-04-13T06:06:15.597+0000] {processor.py:161} INFO - Started process (PID=4153) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:06:15.597+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T06:06:15.599+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:06:15.599+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:06:15.604+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:06:15.603+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T06:06:15.604+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:06:15.622+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.031 seconds
[2024-04-13T06:06:45.947+0000] {processor.py:161} INFO - Started process (PID=4213) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:06:45.949+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T06:06:45.950+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:06:45.950+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:06:45.961+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:06:45.959+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T06:06:45.963+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:06:45.983+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.040 seconds
[2024-04-13T06:07:16.101+0000] {processor.py:161} INFO - Started process (PID=4273) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:07:16.102+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T06:07:16.104+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:07:16.104+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:07:16.111+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:07:16.109+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T06:07:16.111+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:07:16.125+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.031 seconds
[2024-04-13T06:07:46.354+0000] {processor.py:161} INFO - Started process (PID=4333) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:07:46.355+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T06:07:46.358+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:07:46.357+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:07:46.367+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:07:46.365+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T06:07:46.368+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:07:46.383+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.035 seconds
[2024-04-13T06:08:16.507+0000] {processor.py:161} INFO - Started process (PID=4393) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:08:16.508+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T06:08:16.509+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:08:16.509+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:08:16.515+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:08:16.513+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T06:08:16.515+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:08:16.529+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.027 seconds
[2024-04-13T06:08:46.971+0000] {processor.py:161} INFO - Started process (PID=4453) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:08:46.972+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T06:08:46.974+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:08:46.974+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:08:46.982+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:08:46.980+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T06:08:46.982+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:08:46.997+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.033 seconds
[2024-04-13T06:09:17.426+0000] {processor.py:161} INFO - Started process (PID=4513) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:09:17.427+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T06:09:17.429+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:09:17.429+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:09:17.435+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:09:17.434+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T06:09:17.436+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:09:17.449+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.028 seconds
[2024-04-13T06:09:47.636+0000] {processor.py:161} INFO - Started process (PID=4573) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:09:47.637+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T06:09:47.639+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:09:47.639+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:09:47.646+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:09:47.644+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T06:09:47.647+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:09:47.665+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.036 seconds
[2024-04-13T06:10:18.078+0000] {processor.py:161} INFO - Started process (PID=4633) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:10:18.079+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T06:10:18.081+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:10:18.081+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:10:18.087+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:10:18.086+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T06:10:18.088+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:10:18.103+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.032 seconds
[2024-04-13T06:10:48.686+0000] {processor.py:161} INFO - Started process (PID=4693) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:10:48.687+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T06:10:48.689+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:10:48.689+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:10:48.695+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:10:48.694+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T06:10:48.695+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:10:48.724+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.044 seconds
[2024-04-13T06:11:19.427+0000] {processor.py:161} INFO - Started process (PID=4753) to work on /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:11:19.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/verdemar_dag.py for tasks to queue
[2024-04-13T06:11:19.431+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:11:19.430+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:11:19.438+0000] {logging_mixin.py:188} INFO - [2024-04-13T06:11:19.436+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/verdemar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/verdemar_dag.py", line 5, in <module>
    from etl_verdemar import run_etl_process
ModuleNotFoundError: No module named 'etl_verdemar'
[2024-04-13T06:11:19.439+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/verdemar_dag.py
[2024-04-13T06:11:19.457+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/verdemar_dag.py took 0.036 seconds
